# Generated by Django 3.2.2 on 2021-05-06 23:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.casamento_path)),
                ('approved', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
